const $=s=>document.querySelector(s), tasksEl=$('#tasks');
const symbols={USD:'$',EUR:'€',GBP:'£',CAD:'C$',AUD:'A$',NGN:'₦',INR:'₹',ZAR:'R',KES:'KSh ',GHS:'GH₵',SGD:'S$',NZD:'NZ$',JPY:'¥',BRL:'R$'};
const defaults=[['Discovery & planning',4],['Core delivery',24],['Meetings & communication',4],['QA & handoff',4]];
function safe(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function addTask(name='',hours=1){const row=document.createElement('div');row.className='taskrow';row.innerHTML=`<input class="taskname" maxlength="80" aria-label="Deliverable name" placeholder="Deliverable" value="${safe(name)}"><input class="taskhours" type="number" min="0" max="10000" step=".5" aria-label="Estimated hours" value="${hours}"><button class="iconbtn remove" type="button" aria-label="Remove deliverable">×</button>`;tasksEl.append(row);row.querySelector('.remove').onclick=()=>{row.remove();calc()};row.querySelectorAll('input').forEach(x=>x.addEventListener('input',calc))}
function n(id){return Math.max(0,Number($('#'+id).value)||0)}
function money(x){const c=$('#currency').value;return symbols[c]+Math.round(x).toLocaleString()}
function getData(){return {currency:$('#currency').value,rate:n('rate'),project:$('#project').value.trim(),risk:n('risk'),revisions:n('revisions'),expenses:n('expenses'),fee:n('fee'),tax:n('tax'),profit:n('profit'),deposit:n('deposit'),round:n('round'),tasks:[...document.querySelectorAll('.taskrow')].map(r=>[r.querySelector('.taskname').value.trim()||'Deliverable',Math.max(0,Number(r.querySelector('.taskhours').value)||0)])}}
function compute(d){const hours=d.tasks.reduce((s,t)=>s+t[1],0),buffered=hours*(1+d.risk/100),labor=buffered*d.rate,subtotal=labor+d.expenses,withProfit=subtotal*(1+d.profit/100),feeDenom=Math.max(.5,1-d.fee/100),raw=withProfit/feeDenom,quote=Math.ceil(raw/d.round)*d.round,low=Math.ceil((quote*.9)/d.round)*d.round,high=Math.ceil((quote*1.15)/d.round)*d.round;return{hours,buffered,labor,quote,low,high,effective:hours?quote/buffered:0,deposit:quote*d.deposit/100,taxReserve:quote*d.tax/100}}
function track(event){const a=JSON.parse(localStorage.getItem('sr_analytics')||'{"pageviews":0,"calculations":0,"shares":0,"pdfs":0}');a[event]=(a[event]||0)+1;localStorage.setItem('sr_analytics',JSON.stringify(a))}
let timer;function calc(){const d=getData(),r=compute(d);$('#quote').textContent=money(r.quote);$('#range').textContent=`Defensible range: ${money(r.low)}–${money(r.high)}`;$('#hours').textContent=`${r.buffered.toFixed(1)}h`;$('#effective').textContent=`${money(r.effective)}/h`;$('#depositOut').textContent=money(r.deposit);$('#taxOut').textContent=money(r.taxReserve);$('#health').textContent=r.hours===0?'Add your scope to see pricing guidance.':d.risk<15?'Clear scope selected. Confirm exclusions and charge changes separately.':d.risk>=35?'High uncertainty: consider paid discovery or phased pricing before a fixed fee.':'Healthy buffer. Define acceptance criteria and out-of-scope work in writing.';localStorage.setItem('sr_draft',JSON.stringify(d));clearTimeout(timer);timer=setTimeout(()=>track('calculations'),1500);return{d,r}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function proposal(){const {d,r}=calc(),rows=d.tasks.map(t=>`<tr><td>${safe(t[0])}</td><td>${t[1]} hours</td></tr>`).join('');$('#proposal').innerHTML=`<p><strong>ScopeRate estimate</strong></p><h1>${safe(d.project||'Project estimate')}</h1><p>Prepared ${new Date().toLocaleDateString()}. Valid for 14 days.</p><table><thead><tr><th>Deliverable</th><th>Estimated effort</th></tr></thead><tbody>${rows}</tbody></table><p>Includes ${d.revisions} revision round${d.revisions===1?'':'s'} and a ${d.risk}% uncertainty allowance. Work outside the listed scope requires written approval and is billed at ${money(d.rate)} per hour or quoted separately.</p><p class="total">Fixed project fee: ${money(r.quote)}</p><p class="total">Deposit to schedule: ${money(r.deposit)} (${d.deposit}%)</p><h3>Payment & scope notes</h3><ul><li>Deposit is due before work begins.</li><li>Remaining balance is due before final files or launch.</li><li>Client delays may move the delivery schedule.</li><li>This estimate is not a legal contract or tax advice.</li></ul>`;track('pdfs');window.print()}
function load(){const p=new URLSearchParams(location.search);let d;if(p.has('q')){try{d=JSON.parse(decodeURIComponent(escape(atob(p.get('q')))))}catch{toast('That share link is invalid.')}}else{try{d=JSON.parse(localStorage.getItem('sr_draft'))}catch{}}(d?.tasks||defaults).forEach(t=>addTask(t[0],t[1]));if(d){['currency','rate','project','risk','revisions','expenses','fee','tax','profit','deposit','round'].forEach(k=>{if(d[k]!==undefined&&$('#'+k))$('#'+k).value=d[k]})}calc();track('pageviews')}
document.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',calc));$('#addTask').onclick=()=>{addTask();calc()};$('#pdf').onclick=proposal;$('#share').onclick=async()=>{const {d}=calc(),q=btoa(unescape(encodeURIComponent(JSON.stringify(d)))),url=location.origin+location.pathname+'?q='+encodeURIComponent(q);try{await navigator.clipboard.writeText(url);toast('Share link copied');track('shares')}catch{prompt('Copy this link:',url)}};load();
